### ISSUE TITLE
Recursive Array

### ISSUE THREAD

**Issue by kenn** [mooreniemi/array_collapse#2]
Shouldn't a recursive Array raises an error? If there's a self-reference by mistake, I would expect a way to catch that, rather than ignoring it.

**Comment by mooreniemi** [comment]
@kenn that's the choice of the core ruby implementation. as i say [in the readme](https://github.com/mooreniemi/array_collapse#arraycollapse) i made the choice that `collapse` means removing cycles such that you _want_ to be getting a flattened representation.

if you can show me a compelling use case of where you'd want `flatten.compact`'s behavior with raising that error i'd reconsider, but in the meantime you can make use of `flatten.compact` or `flatten.map`

**Comment by kenn** [comment]
Consider building a data structure based on user input. The user might happen to make a self-reference by mistake.

In that case, I would want to notice (with Rollbar / Airbrake / Honeybadger) that there's a poor corner case handling in my app, rather than leaving users puzzled at how it's supposed to work.

That said, probably it's due to the semantics of `flatten` as I feel strongly that it should raise, but given the name `collapse`, it might be ok to squash some unwanted artifacts. :)

I'm closing.
